Add nanoflow event
FlockOfBirds/badge pull request #6
Opened 2018-04-11 09:55 UTC by jseremba

2018-04-11 14:51 UTC, djkwagala requested changes
Reminder to bump your version too. as well as changing it in package-lock.json or running npm i again.

2018-04-11 14:51 UTC, djkwagala commented on src/components/BadgeContainer.ts
> +        }else if (props.onClickEvent === "showPage" && !props.page) {
missing a space between `}` and `else`

2018-04-11 14:51 UTC, djkwagala commented on src/components/BadgeContainer.ts
> +                    mx.ui.error("Error executing nanoflow " + onClickEvent + "callNanoflow" + " : " + error.message);
Please correct the error message 
> \`Error executing nanoflow ${nanoflow} : ${error.message}\`

2018-04-12 13:02 UTC, jseremba commented on src/components/BadgeContainer.ts
> +        }else if (props.onClickEvent === "showPage" && !props.page) {
Added

2018-04-12 13:03 UTC, jseremba commented on src/components/BadgeContainer.ts
> +                    mx.ui.error("Error executing nanoflow " + onClickEvent + "callNanoflow" + " : " + error.message);
Done

2018-05-03 13:19 UTC, merged